server:
  port: 8040
  servlet:
    context-path: /mahuta

logging:
  level:
    ROOT: ERROR
    net.consensys.mahuta: ${LOG_LEVEL:INFO}

mahuta:
  ipfs:
    host: localhost
    port: 5001
#    multiaddress: 
    timeout:
       read: 5000
       write: 2000
    threadPool: 10
    replicaIPFS:
    - host: 
      port: 
    replicaIPFSCluster:
    - host: 
      port: 
    
  elasticsearch:
    host: localhost
    port: 9300
    clusterName: docker-cluster
    indexNullValue: "true"
    indexConfigs:
    - name: 
    
  security:
    cors:
      origins: "*"
      methods: "GET,POST"
      headers: "Origin,Content-Type,Accept"
      credentials: "false"

  api-spec:
    v1:
      query:
        fetch: /query/fetch/{hash}
        search: /query/search
      config:
        index: 
          create: /config/index/{index}
          list: /config/index
      persistence:
        index:
          simple: /index
          cid: /index/cid
          file: /index/file
        delete:
          id: /delete/id/{id}
          hash: /delete/hash/{hash}