version: '2'

services:

  mahuta:
    build: ./
    image: gjeanmart/mahuta:latest
    ports:
    - "8040:8040"
    volumes:
      - ./external-conf.yml:/data/conf.yml
    depends_on:
      - ipfs
      - elasticsearch
    environment:
      WAIT_HOSTS: elasticsearch:9300, ipfs:5001
      CONF: file:///data/conf.yml
      LOG_LEVEL: TRACE
    networks:
      - default

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0 
    ports:
          - "9200:9200"
          - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - default
          
  ipfs:
    image: ipfs/go-ipfs
    ports:
          - "4001:4001"
          - "5001:5001"
          - "8081:8080"